package com.www.service;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.codec.digest.DigestUtils;

public class ChcpService {
	public static void main(String[] args) throws Exception{
		String filePath = "/Users/gm/HotCodeTest/www";
		String outPath = "/Users/gm/HotCodeTest/www";
		String chcpSite = "https://missleslie.cn/www";
		File parent = new File(filePath);
		List<File> list = new ArrayList<File>();
		
		//遍历所有文件
		listFile(parent, list);
		
		//构建
		List<Map<String, String>> chcpList = new ArrayList<Map<String, String>>();
		
		for(File f:list){
			String relativePath = f.getAbsolutePath().replace("\\", "/").replace(filePath, "");
			if(!(relativePath.contains(".svn") || relativePath.endsWith("chcp.json") || relativePath.endsWith("chcp.manifest")||relativePath.endsWith(".ttf"))){
				Map<String, String> map = new HashMap<String,String>();
				map.put("file", relativePath);
				map.put("hash", DigestUtils.md5Hex(new FileInputStream(f)));
				chcpList.add(map);
			}
		}
		
		Map<String, Object> map = new LinkedHashMap<String, Object>();
		map.put("autogenerated", true);
		map.put("release", Common.formatDate(new Date(), "yyyy.MM.dd-HH.mm.ss"));
		map.put("content_url", chcpSite);
		map.put("update", "now");
		
		//生成文件
		FileUtil.deleteFile(outPath + "chcp.manifest");
		FileUtil.deleteFile(outPath + "chcp.json");
		
		FileUtil.createFile(outPath, "chcp.json", JsonCenter.ObjectToPrinter(map), "GB2312");
		FileUtil.createFile(outPath, "chcp.manifest", JsonCenter.ObjectToPrinter(chcpList), "GB2312");
			
		System.out.println("Done");
	}
	
	private static void listFile(File file, List<File> list){
		if(file.isDirectory()){
			for(File son:file.listFiles()){
				listFile(son, list);
			}
		}else{
			list.add(file);
		}
	}
}
